name:                haskell3000
version:             0.1.0.0
github:              "bergsans/haskell3000"
license:             BSD3
author:              "Claes-Magnus Berg"
maintainer:          "claes-magnus@herebeseaswines.net"
copyright:           "MIT"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/bergsans/haskell3000#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  haskell3000-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell3000
